LemonAppDev/konsist

- lib/src/main/kotlin/com/lemonappdev/konsist/api/KoScope.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/KoScopeCreator.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/KoScopeCreatorImpl.kt
Before 
`fun scopeFromPackage(packageName: String): KoScope`
After
`fun scopeFromPackage(packageName: String, module: String? = null, sourceSet: String? = null): KoScope`
> KON-108 Add `module` and `sourceSet` parameters To `KoScopeCreator.scopeFromPackage`

- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture2/Architecture2Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture3/Architecture3Test.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoArchitectureAssert.kt
When we have such dependencies in the project:
and we add this test:
there will be errors.
Error message before PR changes:
Error message after PR changes:
> KON-309 Improve Architecture Assertion Error Messages

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/util/KotlinFileParserTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/util/snippet/file-with-clrf-line-ending.kttxt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoKDocDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoKDocTagsProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/util/EndOfLine.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/util/KotlinFileParser.kt
The Kotlin file parsing is crashing in `org.jetbrains.kotlin:kotlin-compiler` lib. 
Solution - before creating `KtFile` instance the `CLRF` line endings (win) are replaced with `LF` line endings (Unix).
> KON-328 Fix Kotlin File Parsing When File Has CLRF Line Endings

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoLocalClassProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoLocalDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoLocalFunctionProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoLocalPropertyProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkolocalclassprovider/function-contains-local-class.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkolocalfunctionprovider/function-contains-local-function.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkolocalpropertyprovider/function-contains-local-property.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koinitblock/KoInitBlockDeclarationForKoLocalClassProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koinitblock/KoInitBlockDeclarationForKoLocalDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koinitblock/KoInitBlockDeclarationForKoLocalFunctionProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koinitblock/KoInitBlockDeclarationForKoLocalPropertyProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koinitblock/snippet/forkolocalclassprovider/init-block-contains-local-class.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koinitblock/snippet/forkolocalfunctionprovider/init-block-contains-local-function.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koinitblock/snippet/forkolocalpropertyprovider/init-block-contains-local-property.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationListTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationSequenceTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoLocalClassProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoLocalDeclarationProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoLocalFunctionProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoLocalPropertyProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoClassProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoDeclarationProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFunctionProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoInterfaceProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoLocalClassProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoLocalDeclarationProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoLocalFunctionProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoLocalPropertyProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoObjectProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoPropertyProviderCore.kt
Added for all KoLocalXProviders `countLocalX(predicate: (KoXDeclaration) -> Boolean)` and changed `containsLocalX` method to pass predicate function instead of name of declaration.
> KON-335 Add Lambda Param To KoLocalXProvider

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationListTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationSequenceTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/snippet/declaration-assert-displaying-correct-failed-declaration-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/snippet/file-declaration-assert-displaying-correct-failed-declaration-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/KoDeclarationAssertForProviderListTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/snippet/provider-assert-displaying-correct-failed-declaration-type.kttxt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
> KON-339 Refactor KoDeclarationAndProviderAssertCore To Not Display `XCore` In A Failed Declaration Type

- lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoClassDeclaration.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoHasTestProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoHasTestProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoClassDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoHasTestProviderCore.kt
Continue to https://github.com/LemonAppDev/konsist/pull/397
We decided to deprecate previous methods, not remove this.
> KON-361 Deprecate `hasTest`

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationForKoFullyQualifiedNameProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/KoParentDeclarationForKoFullyQualifiedNameProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/parent-fully-qualified-name-without-import.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/KoTypeDeclarationForKoFullyQualifiedNameProviderTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoAnnotationDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPackageDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeDeclarationCore.kt
Assume we have such snippet code:
```kotlin
@SampleAnnotationWithoutImport
fun sampleFunction() {
}
annotation class SampleAnnotationWithoutImport
```
```kotlin
Konsist
.functions()
.withName("sampleFunction")
.annotations
.first()
.fullyQualifiedName // Before it returns empty string, now returns "SampleAnnotationWithoutImport"
```
> KON-373 Update KoFullyQualifiedNameProvider.fullyQualifiedName Implementation To Not Return Empty String

- lib/src/main/kotlin/com/lemonappdev/konsist/api/container/KoScope.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoBaseProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoTextProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/container/KoScopeCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTextProviderCore.kt
Before:
```kotlin
...
.classes()
.print() // prints text and location of all declarations (this causes a mess in the log)
```
After:
```kotlin
...
.classes()
.print { it.name }  // We may choose what we want to display 
// (if we don't pass the predicate in lambda, 
// it prints the declarations as before changes).
```
log to the above:
```kotlin
SampleClass1
SampleClass2
...
```
> KON-381 Add Lambda As Last Argument Of `print` Function

- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoBaseProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoBaseProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoTextProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoBaseProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTextProviderCore.kt
Previously, the `print()` function printed the `toString()` method, which made the log very long, especially for long classes and nested classes.
After change, `print()` prints the `name` declaration (if not available, it prints `toString()`).
Before changes, below snippet code:
```kotlin
Konsist
.classes()
.print("Before changes:")
```
prints:
After changes, below snippet code:
```kotlin
Konsist
.classes()
.print("After changes:")
```
prints:
Developers will be able to print text and other properties by using https://github.com/LemonAppDev/konsist/pull/442.
> KON-382 Change Default Behaviour Of `print`

- lib/src/main/kotlin/com/lemonappdev/konsist/api/container/KoScope.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoBaseProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoBaseProviderExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoBaseProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/container/KoScopeCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoBaseProviderCore.kt
1. Changed return types of `print` method in `KoScope` and `KoBaseProvider` to original element.  Before print() was returning `Unit` which made it impossible to use chain calls.
Before:
After:
2. Add lambda `predicate` parameter to above functions (like in https://github.com/LemonAppDev/konsist/pull/442)
> KON-393 Change Return Type Of `print` From Unit To Declaration Instance

- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoNameProviderListExt.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoNameProviderListExtTest.kt
In `KoNameProvider` we have a property `name` which returns a name - if exists - or an empty string otherwise.
An example of such situation may have `KoArgumentDeclaration` instance:
```kotlin
@SampleAnnotation(sampleParameter = "text") // this annotation has argument with "sampleParameter" name
@SampleAnnotation("text") // this annotation has argument with empty string name 
```
Because of this we improve two extensions:
- `withName()` - we may call this without any argument. It returns list containing elements with non-empty string name.
- `withoutName()` - we may call this without any argument. It returns list containing elements with empty string name.
Before:
After:
> KON-392 Add `withName()` And `withoutName()` Extensions On KoNameProvider List

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/kopropertytype/KoPropertyTypeProviderExtTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/kopropertytype/snippet/declaration-has-complex-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/kopropertytype/snippet/declaration-has-no-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/kopropertytype/snippet/declaration-has-simple-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoPropertyTypeProviderTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoPropertyTypeProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoPropertyTypeProviderExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoPropertyTypeProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoPropertyTypeProviderCore.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoPropertyTypeProviderListExtTest.kt
**Changes:**
1. **Deprecated** `KoPropertyTypeProvider.hasType(name = ...)` and extensions on `KoPropertyTypeProvider` list: `withType(vararg names: String)` and `withoutType(vararg names: String)`.
2. **Added** new methods on `KoPropertyTypeProvider`:
-`fun hasType(predicate: ((KoTypeDeclaration) -> Boolean)? = null): Boolean`
-`fun hasTypeOf(kClass: KClass<*>): Boolean`
3. **Added** new extension on `KoPropertyTypeProvider`: `fun <reified T> KoPropertyTypeProvider.hasTypeOf(): Boolean`
4. **Added** new extensions on `KoPropertyTypeProvider` list:
-`fun <T : KoPropertyTypeProvider> List<T>.withType(predicate: ((KoTypeDeclaration) -> Boolean)? = null): List<T>`
-`fun <T : KoPropertyTypeProvider> List<T>.withoutType(predicate: ((KoTypeDeclaration) -> Boolean)? = null): List<T>` …
> KON-386 KoPropertyTypeProvider Add `hasTypeOf` And `hasType(lambda)`

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoReceiverTypeProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoReceiverTypeProviderTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoPropertyTypeProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoReceiverTypeProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoPropertyTypeProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoReceiverTypeProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoReceiverTypeProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/util/ReceiverUtil.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoPropertyTypeProviderListExtTest.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoReceiverTypeProviderListExtTest.kt
1) Assume that we want to check if all properties in a scope has `String` receiver type.
Before the changes:
```kotlin
Konsist
.properties()
.assert { it.hasReceiverType("String") } 
```
After the changes:
```kotlin
// First option
Konsist
.properties()
.assert { it.hasReceiverTypeOf<String>() } 
// Second option
Konsist
.properties()
.assert { it.hasReceiverTypeOf(String::class) } 
// Third option
Konsist
.properties()
.assert { it.hasReceiverType { type -> type.name == "String" } }
```
2) Similar, we may filter declarations using lambda predicate:
Before the changes:
```kotlin
Konsist
.properties()
.withReceiverType("SampleType1", "SampleType2")
.assert { it.hasPrivateModifier } 
``` …
> KON-410 KoReceiverTypeProvider Add `hasReceiverTypeOf` And `hasReceiverType(lambda)`

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreceivertype/KoReceiverTypeProviderExtTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreceivertype/snippet/declaration-has-no-receiver-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreturntype/KoReturnTypeProviderExtTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreturntype/snippet/declaration-has-no-return-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreturntype/snippet/declaration-has-return-type-with-complex-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreturntype/snippet/declaration-has-return-type-with-simple-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoReturnTypeProviderTest.kt
- lib/src/konsistTest/kotlin/com/lemonappdev/konsist/api/ApiKonsistTest.kt
- lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/DeclarationKonsistTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoReturnTypeProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoPropertyTypeProviderExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoReturnTypeProviderExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoReturnTypeProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoReturnTypeProviderCore.kt
- lib/src/snippet/kotlin/com/lemonappdev/konsist/LibrarySnippets.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoReturnTypeProviderListExtTest.kt
1) Assume that we want to check if all functions in a scope has `String` return type.
Before the changes:
```kotlin
Konsist
.functions()
.assert { it.returnType?.name == "String" } 
```
After the changes:
```kotlin
// First option
Konsist
.functions()
.assert { it.hasReturnTypeOf<String>() } 
// Second option
Konsist
.functions()
.assert { it.hasReturnTypeOf(String::class) } 
// Third option
Konsist
.functions()
.assert { it.hasReturnType { type -> type.name == "String" } }
```
2) Similar, we may filter declarations using lambda predicate:
Before the changes:
```kotlin
Konsist
.functions()
.withReturnType("SampleType1", "SampleType2")
.assert { it.hasPrivateModifier } 
```
After the …
> KON-406 KoReturnTypeProvider Add `hasReturnTypeOf` And `hasReturnType(lambda)`

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationForKoArgumentProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoArgumentProviderTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoArgumentProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoArgumentProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoArgumentProviderCore.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoArgumentProviderListExtTest.kt
After the changes we may:
- count arguments which specify given predicate
```kotlin
Konsist
.functions()
.annotations
.assert {
it.countArguments { argument -> argument.value.startsWith("value") } == 0
}
```
- check if declaration has argument which specified given predicate
```kotlin
Konsist
.functions()
.annotations
.assert {
it.hasArgument { argument -> argument.value == "value" }
}
```
- check if declaration has all arguments which specified given predicate
```kotlin
Konsist
.functions()
.annotations
.assert {
it.hasAllArguments { argument -> argument.value.startsWith("value") }
}
```
- filter declaration using lambda predicate
```kotlin
Konsist
.functions()
.annotations
.withArgument { it.value == "value" …
```
> KON-423 KoArgumentProvider Add `hasArgument(lambda)` `hasAllArguments(lambda)` And `countArguments(lambda)`

- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoKDocTagsProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoKDocTagsProvider.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoKDocTagsProviderListExtTest.kt
**Before changes:**
```kotlin
Konsist
.declarationsOf<KoKDocTagsProvider>()
.flatMap { it.tags }
.assert { // test }
```
**After changes:**
```kotlin
Konsist
.declarationsOf<KoKDocTagsProvider>()
.tags
.assert { // test }
```
The same with `paramTags`, `propertyTags`, `throwsTags`, `exceptionTags`, `sampleTags`, `seeTags`, `authorTags`.
> KON-414 Add Extensions To Expose `tags`

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationListTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationSequenceTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/snippet/declaration-assert-error-with-custom-message.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/snippet/file-declaration-assert-error-with-custom-message.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/KoDeclarationAssertForProviderListTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/KoDeclarationAssertForProviderSequenceTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/snippet/provider-assert-error-with-custom-message.kttxt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/verify/KoDeclarationAndProviderAssert.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/CommonAssert.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
Now, we may add additional message for `assert/assertNot` methods which will be display when test fails. 
**Before**: 
```kotlin 
@Test
fun `sample test`() {
Konsist
.classes
.assert { it.hasPrivateModifier  }
}
```
Error when test fails:
```kotlin
Assert 'sample test' has failed. Invalid files (1):
...
```
**After**:
```kotlin 
@Test
fun `sample test`() {
Konsist
.classes
.assert("CUSTOM ASSERT MESSAGE") { it.hasPrivateModifier  }
}
```
Error when test fails:
```kotlin
Assert 'sample test' has failed.
CUSTOM ASSERT MESSAGE
Invalid files (1):
...
```
This message is optional, if you call `assert/assertNot` methods without this, you will get the same error as before the changes.
> KON-418 Add Message To `assert` And `assertNot`

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/KoImportDeclarationForKoMatchesProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/snippet/forkomatchesprovider/import-matches.kttxt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoImportDeclaration.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoMatchesProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoMatchesProviderCore.kt
Assume we have this import:
```kotlin
import com.lemonappdev.konsist.testdata.SampleType
```
Now, we may write test:
```kotlin
Konsist
.imports
.assert { it.matches("..lemonappdev..testdata..") }  // returns `true` for above import
Konsist
.imports
.assert { it.matches("com") }  // returns `false` for above import
```
> KON-417 Add Provider With `matches` Method

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationListTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationSequenceTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/KoDeclarationAssertForProviderListTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/KoDeclarationAssertForProviderSequenceTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
Before
```
com.lemonappdev.konsist.core.exception.KoCheckFailedException: Assert 'Konsist - adapter package should not access domain package' has failed. Invalid files (1):
```
After
```
com.lemonappdev.konsist.core.exception.KoCheckFailedException: Assert 'Konsist - adapter package should not access domain package' was violated (1 times). Invalid files:
```
> Update Assert Error Message

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoParentProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoParentProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoParentProviderTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoParentProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoParentProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoParentProviderCore.kt
- lib/src/snippet/kotlin/com/lemonappdev/konsist/CleanArchitectureSnippets.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoParentProviderListExtTest.kt
**Example 1**
Assume that we have this class: `class SampleClass : SampleParentClass(), SampleParentInterface` in the `scope`. For this class we have:
```kotlin
scope
.classes()
.assert { 
it.hasParents()  // returns true
it.hasParentWithName("SampleParentClass", "OtherParentClass") // returns true, because SampleClass has at least one parent with given name
it.hasParentsWithAllNames("SampleParentClass", "OtherParentClass") // returns false, because SampleClass has no OtherParentClass parent
it.hasParentsWithAllNames("SampleParentClass", "SampleParentInterface") // returns true, because SampleClass has parents with all given names
it.hasParent { parent -> parent.hasNameEndingWith("Class") } // returns true, because SampleClass has at least one parent which specify predicate …
```
> KON-428 KoParentProvider Add `hasParent` Methods

- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture5/Architecture5Test.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/Layer.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/util/LocationUtil.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt
- I replaced the `WILD_CARD_SYNTAX` with `REGEX_PACKAGE_NAME_END_TWO_DOTS` in `LocationUtil`.
- Added test on `LayerTest` with different endings (and packages names)
I believe that it's a better way to make use of this regex. However, I didn't want to change a lot of things being this my first PR and also my lack of knowledge of the domain.
> Add regex pattern to deal with ending (only) 2 dots at the end of package name

- lib/src/main/kotlin/com/lemonappdev/konsist/core/container/KoScopeCreatorCore.kt
- test-projects/konsist-path-tester/.gradle/caches/GradleCachedKotlinClass.kt
It looks like Gradle can store Kotlin files inside `/.gradle/caches` directory. These are outside project files and have to be ignored.
See https://github.com/LemonAppDev/konsist/discussions/512
> KON-443 Ignore Dot Gradle Directory

- lib/src/konsistTest/kotlin/com/lemonappdev/konsist/api/ApiKonsistTest.kt
- lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/DeclarationKonsistTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoConstructorProviderListExt.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoConstructorProviderListExtTest.kt
Assume we have filter all classes with any constructor. The previous version didn't match to our naming conventions. 
Before:
```kotlin 
Konsist
.classes()
.withConstructor()
```
After:
```kotlin 
Konsist
.classes()
.withConstructors()
```
The same with `withoutConstructors()`.
> KON-457 KoConstructorProviderListExt Change `withConstructor` To `withConstructors` And `withoutConstructor` To `withoutConstructors`

- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoNameProviderListExt.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoNameProviderListExtTest.kt
**Before**
```kotlin
Konsist
.classes()
.withNameStarting("Prefix")
.withNameEnding("Suffix")
.assert { ... }
``` 
or 
```kotlin
Konsist
.classes()
.withNameMatching(Regex(....))
.assert { ... }
``` 
**After**
```kotlin
Konsist
.classes()
.withName { it.startsWith("Prefix") && it.endsWith("Suffix") } 
.assert { ... }
```
> KON-463 Add `withName{}` And `withoutName{}`

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertOnListTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertOnSequenceTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertOnSingleElementTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/snippet/assert-suppress-with-suppress-name-parameter.kttxt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/verify/KoDeclarationAndProviderAssert.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
Issue is that when using Kotest in combination with Konsist, the testName is not been captured due to that the execution of Kotest provides a CustomDSL and it works on a different context from which the name cannot be caught in the current way with konsist.
- Add `suppressName` to test for KoTest context.
Usage:
- Class with Suppress annotation:
```
@Suppress("endWithResource")
class TestResource {
...
}
```
- Test
```
...
import io.kotest.core.spec.style.FreeSpec // using kotest. Others imports not shown for simplicity
...
class ArchitectureTest: FreeSpec({
"endWithResource" {
Konsist
.classes()
.withNameEndingWith("Resource")
// adding suppressName grabbing from context (this) the testCase name
.assert(suppressName = this.testCase.name.testName) { …
```
> add suppress name for assert with KoTest context

- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoAbstractModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoActualModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoAnnotationModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoCompanionModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoConstModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoCrossInlineModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoDataModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoEnumModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoExpectModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoExternalModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoFinalModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoFunModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoInfixModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoInlineModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoInnerModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoLateinitModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoNoInlineModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoOpenModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoOperatorModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoOverrideModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoSealedModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoSuspendModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoTailrecModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoValueModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoVarArgModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoVisibilityModifierProviderCore.kt
- Remove deprecated `.hasmodifiers()` from internal providers
> KON-496 - Remove deprecated `.hasmodifiers()`

- buildSrc/src/main/kotlin/local.base.gradle.kts
- buildSrc/src/main/kotlin/local.javalibrary.gradle.kts
- lib/build.gradle.kts
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/CommonAssert.kt
Revert the Java version to `8`.
Reasons:
- `Java 9` and `Java 10` were non-LTS(Long time support) releases, meaning `Java 8` has a longer maintenance cycle
- `Java 9` is not officially supported on MacOs anymore.
- `Java 9` was introduced in `Android 9`, so some Android apps will most likely target this Android version to allow this version. We could have an Androdi module targeting `Java 8` and a dedicated Konsist module with `Java 9` versions, however, multiple Java versions lead to Gradle build issues.
- Stack Walker API does not provide any benefit, besides a bit clearer API
**Android Java Info**
- Android 13 has access to Java 8, 9, 11, and 17
- Android 11 and 12 have access to Java 8, 9, and 11
- Android Pie (9) and 10 has access to Java 8 and 9
- Android Oreo (8) has access to Java …
> Revert Stack Walker

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoBodyProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkobodyprovider/function-has-block-body.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkobodyprovider/function-has-expression-body.kttxt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoFunctionDeclaration.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoBodyProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoBodyProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoBodyProviderCore.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoBodyProviderListExtTest.kt
We now have access to information whether the function has an expression or block body:
```kotlin
Konsist
.scopeFromProduction()
.functions()
.assertTrue { it.hasBlockBody } 
```
We may also filtering the declarations by whether they have expression or block body:
```kotlin
Konsist
.scopeFromProduction()
.functions()
.withBlockBody()
.assertTrue { it.hasReturnType() } 
```
> KON-507 Add `hasExpressionBody` And `hasBlockBody` To KoFunctionDeclaration

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoReturnTypeProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-block-body-and-declared-type-has-string-return-value.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-block-body-and-declared-type-has-unit-return-value.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-block-body-and-without-declared-type-has-unit-return-value.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-expression-body-and-declared-type-has-string-return-value.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-expression-body-and-declared-type-has-unit-return-value.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-expression-body-and-without-declared-type-has-string-return-value.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-expression-body-and-without-declared-type-has-unit-return-value.kttxt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoReturnTypeProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoReturnTypeProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoReturnTypeProviderCore.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoReturnTypeProviderListExtTest.kt
We may call `hasReturnValue` on function declaration to check if has non-Unit return value (but this function doesn't have to explicitly specifies a return type).
E.g.
- with block body
-  for `fun sampleFunction() { "some text" }`  - `hasReturnValue` returns `false`
- 	for `fun sampleFunction(): Unit { "some text" }`  - `hasReturnValue` returns `false`
-  for `fun sampleFunction(): String { return "some text" }`  - `hasReturnValue` returns `true`
- with expression body
-  for `fun sampleFunction() = SampleClass()`  - `hasReturnValue` returns `true`
-  for `fun sampleFunction() = println("some text")`  - `hasReturnValue` returns `true` - **it is an exception!**
-  for `fun sampleFunction(): SampleClass = SampleClass()`  - `hasReturnValue` returns `true`
-  for `fun sampleFunction(): Unit …
> KON-203 Add `hasReturnValue` To KoFunctionDeclaration

- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture1/Architecture1Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture2/Architecture2Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture3/Architecture3Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture4/Architecture4Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture5/Architecture5Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture6/Architecture6Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture7/Architecture7Test.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/KoArchitectureAssertion.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/KoArchitectureAssertionCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/KoArchitectureScope.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoArchitectureAssert.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
Add `.assert()` for files within the Scope of an architecture.
- Refactor in order to prevent code duplication
- Add new `internal class` for  `List<KoFileDeclaration>` for `KoArchitectureScope` (KoArchitectureFiles)
- Add new methods to `KoArchitectureAssertion`
- Add tests for files
- Added method for validate some structures of the files. The `assert()` method for `files` and `scope` is fairly similar, but if it's extracted to a new one, the exception is behaving not correcting make it fails.
> KON-257 Add assert architecture on list of files

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoBodyProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkobodyprovider/function-has-no-body.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kogetter/KoGetterDeclarationForKoBodyProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kogetter/snippet/forkobodyprovider/getter-has-no-body.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kosetter/KoSetterDeclarationForKoBodyProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kosetter/snippet/forkobodyprovider/setter-has-no-body.kttxt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoBodyProviderCore.kt
**Snippet:**
```kotlin
interface SampleInterface {
fun sampleFunction()
}
```
**Behaviour before changes**
`hasBlockBody` returns `true` for `sampleFunction`
**Behaviour after changes**
`hasBlockBody` returns `false` for `sampleFunction`
> KON-532 `hasBlockBody` In KoBodyProvider Returns True When Declaration Has No Body

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationForKoRepresentsTypeProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoRepresentsTypeProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoRepresentsTypeProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoRepresentsTypeProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/KoParameterDeclarationForKoRepresentsTypeProviderTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoRepresentsTypeProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoRepresentsTypeProviderExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoRepresentsTypeProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParameterDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoRepresentsTypeProviderCore.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoRepresentsTypeProviderListExtTest.kt
This commit allows passing `null` values to the function `representsType()` which will result in a `false` response.
Those changes would allow the consumers of the library to replace the following implementation:
```kotlin
@Test
fun `fields for a particular type are of the interface`() {
val interfaces = scope.interfaces()
scope
.classes()
.withPackage("..domain..")
.properties()
// .with...
.assertTrue {
val propertyTypeFQN = it.type?.fullyQualifiedName ?: return@assertTrue false
interfaces.any { interfacee ->
interfacee.representsType(propertyTypeFQN)
}
}
}
```
With this one:
```kotlin
@Test
fun `fields for a particular type are of the interface`() {
val interfaces = scope.interfaces()
scope
.classes()
.withPackage("..domain..")
.properties()
// .with...
.assertTrue {
interfaces.any { …
```
> KON-553: Allow `null` values in representsType()

- .github/workflows/check-kttxt-snippets.yml
- .github/workflows/check-starter-projects.yml
This commit ensures that each PR would run maximum of 1 CI pipeline in parallel, if a new commit was pushed into the PR, the previous pipeline execution would be cancelled in favor of the new one.
The change was applied only PR related as we might want to run multiple PRs on main when it is merged from the develop branch
> KON-563: Run only 1 CI pipeline in parallel for each PR

- lib/src/main/kotlin/com/lemonappdev/konsist/core/util/LocationUtil.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt
Since this regex was changed, defining a layer implies using the full name and adding two dots at the end. With this, we allow using .. as wildcard.
- com.acme.ui.. :white_check_mark:
- com.acme..feature1.. :white_check_mark:
- com.acme..feature2.. :white_check_mark:
- com.acme..feature3 :x:
> Replace REGEX to allow using .. as wildcard again

- .github/workflows/check-kttxt-snippets.yml
- scripts/check_kttxt_snippets.py
This commit changes the behavior of CI for snippets, by checking only the list of changed files as part of the snippets that are tested.
If no list has been provided from CI, all snippets would be tested (to support a release process)
---
This PR was tested by disabling the rules that enforce the pipeline to run only after specific conditions and ensuring that it correctly picks up the values.
Moreover, it was tested locally by passing the snippet and checking that only this snippet was picked up.
> KON-562: Improve snippet CI verification

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/KoTypeDeclarationForKoSourceAndAliasTypeProviderTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoSourceAndAliasTypeProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoSourceAndAliasTypeProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFullyQualifiedNameProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoKotlinTypeProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSourceAndAliasTypeProviderCore.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoSourceAndAliasTypeProviderListExtTest.kt
- rename `baseSourceType` To `bareSourcetype`
- type does not have nullability information
> KON-570 Rename `baseSourceType` To `bareSourcetype`

- lib/src/main/kotlin/com/lemonappdev/konsist/core/filesystem/rootprovider/GitProjectRootDirResolver.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/core/filesystem/rootprovider/GitProjectRootDirResolverTest.kt
In projects dependent on resolving project directory based on git the following exception would be thrown:
```
com.lemonappdev.konsist.core.exception.KoInternalException: Project directory not found. Searched in /<your-directory-here> and parent directories
```
because the paths defined in `GitProjectRootDirResolver` didn't point to the `.git` directory, but rather a `git` repository missing the `.`.
> Fix git dir resolver uses the wrong paths

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/import-alias.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/list-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/non-nullable-type-without-import-and-package.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/non-nullable-type-without-import-and-with-package.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/nullable-import-alias.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/nullable-list-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/nullable-type-without-import-and-package.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/nullable-type-without-import-and-with-package.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/nullable-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/type.kttxt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFullyQualifiedNameProviderCore.kt
`fullyQualifiedName` was broken, because it tries to match first import which CONTAINS the expected type name. Ex: `org.AnotherPerson` contains `Person`, but should matches this predicate, but it not the fully qualified name or `Perso`.
I chose to update existing snippets used in `KoTypeDeclarationForKoFullyQualifiedNameProviderTest`, instead of trying to build all possible combinations :
* current list of use cases
* with or without another import… which name start, contains or ends with expected `fullyQualifiedName` … or not
I think it's preferable.
> KON-578 Fix fully qualified name

- lib/src/main/kotlin/com/lemonappdev/konsist/core/util/LocationUtil.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt
Fixed bug reported at: https://github.com/LemonAppDev/konsist/discussions/765.
> KON-577 Layer doesn't allow string that uses a package wildcard twice

- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoPackageMatchingPathProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/util/PathUtil.kt
- test-projects/konsist-declaration-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kopackage/KoPackageDeclarationForKoPackageMatchingPathProviderTest.kt
- test-projects/konsist-declaration-tester/app/src/main/kotlin/com/lemonappdev/sample/AppClassWithPackageNotMatchingPath.kt
- test-projects/konsist-declaration-tester/app/src/main/kotlin/com/lemonappdev/sample/AppClassWithPackageNotMatchingToPath.kt
- test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/helper/ext/PathExt.kt
Fixed bug reported at: https://github.com/LemonAppDev/konsist/discussions/864
> KON-593 `KoPackageMatchingPathProviderCore.hasMatchingPath` fails on windows

- gradle/libs.versions.toml
Prerelease version of Kotlin makes project using release version incompatible. We need to use official version.
> Restore Kotlin Version

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoSourceDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-class-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-external-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-function-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-import-alias-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-interface-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-kotlin-basic-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-kotlin-collection-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-object-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-typealias-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-class-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-external-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-function-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-import-alias-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-interface-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-kotlin-basic-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-kotlin-collection-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-object-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-typealias-type.kttxt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/testdata/TestData.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/type/KoTypeDeclaration.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoSourceDeclarationProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoSourceDeclarationProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoTypeDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSourceDeclarationProviderCore.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoSourceDeclarationProviderListExtTest.kt
Now `KoTypeDeclaration` has access to properties:
- `sourceDeclaration: KoBaseTypeDeclaration`
- `sourceClass: KoClassDeclaration?`
- `sourceObject: KoObjectDeclaration?`
- `sourceInterface: KoInterfaceDeclaration?`
- `sourceTypeAlias: KoTypeAliasDeclaration?`
- `sourceImportAlias: KoImportAliasDeclaration?`
- `sourceKotlinType: KoKotlinTypeDeclaration?`
-  `sourceFunctionType: KoFunctionTypeDeclaration?`
- `sourceExternalType: KoExternalDeclaration?` . 
There is no need to cast `sourceDeclaration` to a specific type because Konsist provides us with dedicated properties.
Eg. Instead of writing:
```kotlin
scope
.functions()
.returnTypes
.map { it.sourceDeclaration as? KoClassDeclaration }
.assertTrue { // ... }
```
you can do in this way:
```kotlin
scope
.functions()
.returnTypes …
```
> KON-596 Add extensions to retrieve properties of the source type

- lib/src/main/kotlin/com/lemonappdev/konsist/core/util/TypeUtil.kt
Added `Unit`, `Any` and `Nothing` to kotlin types
> Add Missing Kotlin Basic Types - `Unit`, `Any` and `Nothing`

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/KoImportAliasDeclarationForKoContainingDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/KoImportAliasDeclarationForKoContainingFileProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/KoImportAliasDeclarationForKoLocationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/KoImportAliasDeclarationForKoNameProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/KoImportAliasDeclarationForKoPackageProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/KoImportAliasDeclarationForKoPathProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/KoImportAliasDeclarationForKoResideInPackageProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/KoImportAliasDeclarationForKoTextProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/KoImportAliasDeclarationTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/KoFunctionTypeDeclarationForKoContainingDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/KoFunctionTypeDeclarationForKoContainingFileProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/KoFunctionTypeDeclarationForKoLocationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/KoFunctionTypeDeclarationForKoNameProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/KoFunctionTypeDeclarationForKoPackageProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/KoFunctionTypeDeclarationForKoPathProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/KoFunctionTypeDeclarationForKoResideInPackageProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/KoFunctionTypeDeclarationForKoTextProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/KoFunctionTypeDeclarationTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kokotlintype/KoKotlinTypeDeclarationForKoFullyQualifiedNameProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kokotlintype/KoKotlinTypeDeclarationForKoNameProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kokotlintype/KoKotlinTypeDeclarationForKoPackageProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kokotlintype/KoKotlinTypeDeclarationForKoResideInPackageProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kokotlintype/KoKotlinTypeDeclarationForKoTextProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kokotlintype/KoKotlinTypeDeclarationTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoGenericTypeProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSourceAndAliasTypeProviderCore.kt
- test-projects/konsist-declaration-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koimportalias/KoImportAliasForKoModuleProviderTest.kt
- test-projects/konsist-declaration-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koimportalias/KoImportAliasForKoSourceSetProviderTest.kt
- test-projects/konsist-declaration-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/type/kofunctiontype/KoFunctionTypeForKoModuleProviderTest.kt
- test-projects/konsist-declaration-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/type/kofunctiontype/KoFunctionTypeForKoSourceSetProviderTest.kt
Use into a Konsist code dedicated properties `sourceX` instead of `?.sourceDeclaration as? KoXDeclaration`
> Use `sourceX` Properties

- .github/workflows/check-path.yml
- .github/workflows/check.yml
`macos-latest` image from github actions was migrated from [macos-14](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md) to [macos-14-arm64](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md) (see [README of github actions
runner-images](https://github.com/actions/runner-images/commit/84c158e8b8f516478f045f9712856e6c65c526b3) and [github blog](https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/)).
Java `8` is installed in `macos-14`, but not in `macos-14-arm64`, and all jobs on macos images require java `8` and java `21`.
> Fix CI jobs on macos-latest after github actions image migration

- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture1/Architecture1Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture2/Architecture2Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture3/Architecture3Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture4/Architecture4Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture5/Architecture5Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture7/Architecture7Test.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/DependencyRules.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/DependencyRulesCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoArchitectureAssert.kt
Added `doesNotDependOn` method to architectural checks. 
Eg. It is possible to write such tests for this architecture
```kotlin
private val scope = Konsist.scopeFromProject()
private val adapter = Layer("Adapter", "com.samplepackage.adapter..")
private val common = Layer("Common", "com.samplepackage.common..")
private val domain = Layer("Domain", "com.samplepackage.domain..")
private val port = Layer("Port", "com.samplepackage.port..")
@Test
fun `Domain layer not depend on Adapter and Port layers and Adapter layer not depend on Domain layer`() {
scope.assertArchitecture { 
domain.doesNotDependOn(adapter, port)
adapter.doesNotDependOn(domain)
}
}
```
> KON-623 Add `doesNotDependOn` to layer verification

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/korepresentstype/KoRepresentsTypeProviderExtTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/korepresentstype/snippet/import-represents-complex-type.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/korepresentstype/snippet/import-represents-kotlin-type.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/KoImportDeclarationForKoRepresentsTypeProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/snippet/forkorepresentstypeprovider/import-represents-complex-type.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/snippet/forkorepresentstypeprovider/import-represents-kotlin-type.kttest
- lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoImportDeclaration.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportDeclarationCore.kt
Added `KoRepresentsTypeProvider` for `KoImportDeclaration`. Now, it's possible to write tests like below:
```kotlin
// 1
scope
.files
.withImport { it.representsType<SampleType>() }
.assertTrue { ... }
// 2
scope
.imports
.withRepresentedType("SampleType")
.assertTrue { ... }
```
> KON-605 KoImportDeclaration add represents type

- .github/workflows/check-ktdoc-snippets.yml
- .github/workflows/check-kttest-snippets.yml
- .github/workflows/check-starter-projects.yml
When PR is opened from forked repository it some job are failing. This PR is an attempt to fix this issue by updating jobs permissions.
Failing Jobs:
> Fix Jobs that are failing forked repositories external 

- lib/src/main/kotlin/com/lemonappdev/konsist/api/KoModifier.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/modifierprovider/KoFunModifierProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/modifier/KoFunModifierProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoFunModifierProviderCore.kt
Reversed because interface can have `fun` modifier
```kotlin
fun interface A {
fun a()
}
```
> Revert "KON-653 Deprecate `KoModifier.FUN`"

- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/dependencyrules/DependencyRulesTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/DependencyRulesCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoArchitectureAssert.kt
- store layers in `Set`
- rename `checkX` methods to `requireX`
- rename `Status` to `LayerDependencyType`
- simplify `requireNoCircularDependencies` method (previously `checkIfLayerHasTheSameValuesAsOtherLayer`)
> Refactor Architecture Assertions

- lib/src/main/kotlin/com/lemonappdev/konsist/core/util/TypeUtil.kt
- Add Number Type to Kotlin basic types
- Represent Type as Kotlin Types not as Strings
> KON-675 Add `Number` Type Basic Kotlin Types

- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/modifierprovider/KoValModifierProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/modifierprovider/KoVarModifierProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/modifier/KoValModifierProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/modifier/KoVarModifierProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/annotation/RemoveInVersion.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParameterDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoVariableDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/combined/KoClassAndInterfaceAndObjectDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoTypeDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoDeclarationCastProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoValModifierProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoVarModifierProviderCore.kt
- scripts/create_release.py
1. The version in deprecated declarations in this version has been updated from `0.18.0` to `0.19.0` to correct a previous error.
2. The `@RemoveInVersion` annotations have been introduced to mark code elements that are not currently deprecated but will be unnecessary in a future version. For example:
```kotlin
@RemoveInVersion("0.18.0")
override val isInitialized: Boolean by lazy { super<KoIsInitializedProviderCore>.isInitialized }
```
This addition addresses the current situation where there are two providers (one deprecated) that provide the same declaration, necessitating the specification of which implementation to consider. Once the deprecated element is removed, these declarations will no longer be required.
3. The Python code for creating releases has been updated to check for …
> KON-668 Change the version of deleting declarations annotated as deprecated in this release from 0.18.0 to 0.19.0

- detekt.yml
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture1/Architecture1Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture2/Architecture2Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture4/Architecture4Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture5/Architecture5Test.kt
- lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture7/Architecture7Test.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/LayerDependencies.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependenciesCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependencyType.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoArchitectureAssert.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependenciesCoreTest.kt
```kotlin
assertArchitecture {
layer.include()
}
```
Allow to include layer when using `dependsOnNothing`
> KON-678 Add Layer Include

- lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/EnumKonsistTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/LayerDependencies.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependenciesCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependency.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependencyType.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/CircularDependencyDependenciesRule.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/DependOnLayerThenDependentOnNothingRule.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/DependentOnNothingThenDependOnLayerDependenciesRule.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependenciesCoreTest.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependencyTest.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/CircularDependencyDependenciesRuleTest.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/DependOnLayerThenDependentOnNothingRuleTest.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/DependentOnNothingThenDependOnLayerDependenciesRuleTest.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/UniqueLayerRuleTest.kt
```kotlin
val sourceLayer1 = Layer("Domain", "com.example.domain..")
val sourceLayer2 = Layer("Data", "com.example.data..")
val sourceLayers = setOf(sourceLayer1, sourceLayer2)
val targetLayer = Layer("Presentation", "com.example.presentation..")
...
assertArchitecture {
// Call dependsOn, doesNotDependOn, dependsOnNothing, include on collections
sourceLayers.dependsOn(targetLayer)
}
```
> KON-679 Allow To Call Layer Dependency Method On Collections

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/KoTypeArgumentDeclarationForKoFunctionTypeDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/snippet/forkofunctiontypedeclarationprovider/parameters-list-has-one-element-with-name.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoFunctionTypeDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkofunctiontypedeclarationprovider/parameters-list-has-one-element-with-name.kttest
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoFunctionTypeDeclarationProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoFunctionTypeDeclarationProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFunctionTypeDeclarationProviderCore.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoFunctionTypeDeclarationProviderListExtTest.kt
In this PR, all methods related to `parameterTypes` in `KoFunctionTypeDeclarationProvider` have been deprecated. Instead, equivalent methods with the name `parameters` have been added to the provider. Similar changes have been applied to the extensions for this provider.
// Example 1 
```kotlin
// Before
scope
.functions()
.returnTypes
.assertTrue { it.parameterTypes?.isEmpty() }
// After
scope
.functions()
.returnTypes
.assertTrue { it.parameters?.isEmpty() }
```
// Example 2 
```kotlin
// Before
scope
.functions()
.returnTypes
.assertTrue { it.countParameterTypes { param -> param.name == "sampleParameter" } == 1 } 
// After
scope
.functions()
.returnTypes
.assertTrue { it.countParameters { param -> param.name == "sampleParameter" } == 1 } 
```
// Example 3 
```kotlin
// Before
scope …
```
> KON-658 Change structure of parameter types in KoFunctionTypeDeclarationProvider

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/KoParentDeclarationForKoDeclarationCastProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/KoTypeArgumentDeclarationForKoDeclarationCastProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kostarprojection/KoStarProjectionDeclarationForKoDeclarationCastProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoDeclarationCastProviderTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoDeclarationCastProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoDeclarationCastProvider.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoDeclarationCastProviderCore.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoDeclarationCastProviderListExtTest.kt
This PR introduces a comprehensive set of functionalities to enhance type handling within `KoDeclarationCastProvider`, focusing on combined types like classes, interfaces, and objects. The changes aim to improve the clarity, usability, and flexibility of declarations, making it easier to work with complex type combinations in Kotlin.
1. **New Properties**:  
Added Boolean properties such as `isClassOrObject`, `isClassOrInterface`, and similar, to allow quick identification of declarations that belong to combined type categories (e.g., whether a declaration is either a class or an object).
2. **New Methods for Casting**:  
Introduced methods like `asClassOrObjectDeclaration()` or `asClassOrInterfaceDeclaration()` that enable safe casting to specific combined types. This ensures clear and …
> KON-685  Add missing declaration in KoDeclarationCastProvider for combined types

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/KoParentDeclarationForKoSourceDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/class-with-parent-class-with-the-same-name.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/class-with-parent-interface-with-the-same-name.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/interface-with-parent-interface-with-the-same-name.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/object-with-parent-class-with-the-same-name.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/object-with-parent-interface-with-the-same-name.kttest
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/model/DataCore.kt
Community: https://github.com/LemonAppDev/konsist/discussions/1292
> KON-692 Fix "StackOverflowError" Exception when trying to find indirect parents

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertempty/AssertEmptyOnDeclarationListTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertempty/AssertEmptyOnDeclarationSequenceTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertempty/AssertEmptyOnProviderListTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertempty/AssertEmptyOnProviderSequenceTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
**Enhancements** - Added ASCII tree and hyperlinks to improve error messages for missing methods.  
**Updated Methods** - `assertNotEmpty`, `assertEmpty`, `assertNull`, `assertNotNull`
**Before:**
**After:**
> KON-693 Add ASCII tree to missing methods like assertNotEmpty

- lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/Layer.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt
In Konsit 0.17.0  wildcards while defining Layer got broken.
Restore Konsist `0.16.1` behaviour allowing layer definition with two dots at the beginning
```kotlin
Layer("Domain", "..domain..")
```
> KON-699 Restore Layer Package Validation

- lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/Layer.kt
- lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt
Accept camelCase regarding Kotlin guidelines:
> Package and class naming rules in Kotlin are quite simple:
> 
> Names of packages are always lowercase and do not use underscores (org.example.project). Using multi-word names is generally discouraged, but if you do need to use multiple words, you can either just concatenate them together or use camel
https://kotlinlang.org/docs/coding-conventions.html#naming-rules
> Update layer package convention naming

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoClassProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoFunctionProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoPropertyProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkoclassprovider/enum-constant-contains-class.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkoclassprovider/enum-constant-contains-no-classes.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkodeclarationprovider/enum-constant-contains-declarations.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkodeclarationprovider/enum-constant-contains-nested-and-local-declarations.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkodeclarationprovider/enum-constant-contains-no-declarations.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkofunctionprovider/enum-constant-contains-function.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkofunctionprovider/enum-constant-contains-no-function.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkopropertyprovider/count-properties.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkopropertyprovider/enum-constant-contains-nested-properties.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkopropertyprovider/enum-constant-has-no-properties.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkopropertyprovider/enum-constant-has-two-properties.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoDeclarationProviderTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoEnumConstantDeclaration.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/DepracatedKoLocalClassProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/DeprecatedKoLocalDeclarationProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/DeprecatedKoLocalFunctionProviderListExt.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoEnumConstantDeclarationCore.kt
**Changes:**  
- Deprecated support for variables and local declarations in `KoEnumConstantDeclaration`.  
- Added support for properties and other declarations in `KoEnumConstantDeclaration`.  
Previously, `KoEnumConstantDeclaration` provided access to properties, functions and extensions for variables, local declarations and local functions. However, this behaviour was incorrect and has now been deprecated. Instead, new providers have been introduced to access properties, functions and extensions specifically for declarations, properties, functions and classes.
Community: https://github.com/LemonAppDev/konsist/discussions/1596
**Examples:**
- Use `hasProperty { ... }` instead of `hasVariable { ... }`
**Before:**
```kotlin
Konsist
.classes()
.enumConstants
.assertTrue …
```
> KON-695 Add missing providers for `KoEnumContantDeclaration`

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/KoParentDeclarationForKoSourceDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/class-with-parent-class-with-two-part-name-from-import.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/class-with-parent-class-with-two-part-name-from-the-same-file.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/class-with-parent-interface-with-two-part-name-from-import.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/class-with-parent-interface-with-two-part-name-from-the-same-file.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/interface-with-parent-interface-with-two-part-name-from-import.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/interface-with-parent-interface-with-two-part-name-from-the-same-file.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/object-with-parent-class-with-two-part-name-from-import.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/object-with-parent-class-with-two-part-name-from-the-same-file.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/object-with-parent-interface-with-two-part-name-from-import.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/object-with-parent-interface-with-two-part-name-from-the-same-file.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/testdata/TestData.kt
- lib/src/konsistTest/kotlin/com/lemonappdev/konsist/api/ApiKonsistTest.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentDeclarationCore.kt
This PR fixes a bug in resolving parent declarations with complex names (e.g., `SampleInterface.SampleClass`) when they are imported into a file. Previously, instead of finding the correct declaration (e.g., `KoClassDeclaration`), the system would incorrectly return a `KoExternalDeclaration`.
Community: https://github.com/LemonAppDev/konsist/discussions/1616
> KON-701 Fix incorrect sourceDeclaration resolution for inner classes in parent declarations

- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationForKoFullyQualifiedNameProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationForKoSourceDeclarationProviderTest.kt
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkofullyqualifiednameprovider/annotation-fully-qualified-name-with-import-alias.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkosourcedeclarationprovider/annotation-with-imported-source-declaration.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkosourcedeclarationprovider/annotation-with-kotlin-source-declaration-with-default-import.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkosourcedeclarationprovider/annotation-with-kotlin-source-declaration-without-default-import.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkosourcedeclarationprovider/annotation-with-source-declaration-defined-in-the-file-with-package.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkosourcedeclarationprovider/annotation-with-source-declaration-defined-in-the-file-without-package.kttest
- lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkosourcedeclarationprovider/annotation-with-source-declaration-defined-using-import-alias.kttest
- lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoAnnotationDeclaration.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoAnnotationDeclarationCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSourceDeclarationProviderCore.kt
- lib/src/main/kotlin/com/lemonappdev/konsist/core/util/TypeUtil.kt
```kotlin
Konsist
.scopeFromProduction()
.classes()
.annotations
.assertTrue { it.sourceDeclaration?.hasNameContaining("Sample") }
```
Declarations can also be filtered based on whether their source declaration satisfies a given predicate.
```kotlin
Konsist
.scopeFromProduction()
.classes()
.annotations
.withSourceDeclaration { it.hasNameContaining("Sample") }
.assertTrue { ... } 
```
**Kotlin code:**
```kotlin
import com.domain.example.ExampleAnnotation as AnnotationAliased
@AnnotationAliased
class ExampleUseCase
```
**Konsist code:**
```kotlin
val annotationFullyQualifiedNames = Konsist
.classes()
.withName("ExampleUseCase")
.first()
.annotations
.map { it.fullyQualifiedName }
```
**Before:** `annotationFullyQualifiedNames` returns `["AnnotationAliased"]`
**After:** …
> KON-704 Add source declarations to `KoAnnotationDeclaration`
