LemonAppDev/konsist

.gitbook.yaml
Docs moved to https://github.com/LemonAppDev/konsist-documentation
=> Remove gitbook (#70

lib/src/main/kotlin/com/lemonappdev/konsist/core/ext/KoComplexDeclarationSequenceExt.kt, lib/src/test/kotlin/com/lemonappdev/konsist/core/ext/KoComplexDeclarationSequenceExtTest.kt
- add extensions for providers
- fix spotless
=> KON-65 KoComplexDeclaration Add Extensions For Providers (#72

lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoAnnotation.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/ext/KoBaseDeclarationSequenceExt.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/ext/KoComplexDeclarationSequenceExt.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/ext/KoDeclarationSequenceExt.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/ext/KoNamedDeclarationSequenceExt.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/ext/KoParametrizedDeclarationSequenceExt.kt
- add extensions for providers
- fix spotless
- use generics in all open or abstract classes
=> KON-78 Change All Extensions To Use Generics (#73

lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoComplexDeclaration.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFile.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunction.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/provider/KoDeclarationProvider.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/provider/KoDeclarationProviderUtil.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/provider/KoLocalDeclarationProvider.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/PrintDeclarations.kt, lib/src/test/kotlin/com/lemonappdev/konsist/core/declaration/kocomplexdeclaration/KoComplexDeclarationForClassTest.kt, lib/src/test/kotlin/com/lemonappdev/konsist/core/declaration/kocomplexdeclaration/KoComplexDeclarationForCompanionObjectTest.kt, lib/src/test/kotlin/com/lemonappdev/konsist/core/declaration/kocomplexdeclaration/KoComplexDeclarationForInterfaceTest.kt, lib/src/test/kotlin/com/lemonappdev/konsist/core/declaration/kocomplexdeclaration/KoComplexDeclarationForObjectTest.kt, lib/src/test/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionTest.kt, lib/src/test/kotlin/com/lemonappdev/konsist/core/ext/KoComplexDeclarationSequenceExtTest.kt, lib/src/test/kotlin/com/lemonappdev/konsist/core/verify/PrintDeclaration.kt
- update printDeclarations method
- change return collections from List to Sequence
- fix spotless
=> KON-82 KoDeclarationProvider Should Return Sequence Instead Of List

lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/util/PackageHelperTest.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/KoScopeCreatorImpl.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoDeclarationImpl.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFileDeclarationImpl.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPsiDeclarationImpl.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/ext/FileExt.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/util/KotlinFileParser.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/util/PackageHelper.kt, misc/DeveloperReadme.md
- Move Utils to Core
- Add Diagram
=> KON-105 Move `utils` To `core`

.github/workflows/check-kttxt-snippets.yml, scripts/check-kttxt-snippets.py
Remove `data object` validation bypass
=> Update `check-kttxt-snippets.py` for Kotlin 1.9

.github/workflows/check-kttxt-snippets.yml, lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt, scripts/check-kttxt-snippets.py
- compile kttxt snippets in parallel 
- provide instant output (SUCCESS / FAILED)
- Change Location of check-kttxt-snippets script generated classes (files are not saved on disk anymore)
closes #568
=> KON-238 Improve snippet verification script

DeveloperReadme.md
Move some parts to https://app.gitbook.com/o/PQj191UX5M2C2XxCZuYO/s/RYeSMx6WDKivnwWx7PdP/help/contributing
=> Update Dev Readme

lib/src/integrationTest/kotlin/com/lemonappdev/konsist/TestSnippetProvider.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/util/KotlinFileParser.kt
Display path of the file that Konsist can't parse
=> KON-535 Improve Error Message For Ktfile Creation

lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/KoTypeDeclarationForKoSourceAndAliasTypeProviderTest.kt, lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/SampleProperty.kt, lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/fully-qualified-type.kttxt, lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoSourceAndAliasTypeProvider.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSourceAndAliasTypeProviderCore.kt
```kotlin
// Code
val myClass:com.app.MyClass? = null()
// KonsistAPI
koProperty.type. bareType // MyClass
````
For `com.app.MyClass` value will be "MyClass"
=> KON-570 Remove Package From `bareType`

.github/workflows/check-kttxt-snippets.yml, .github/workflows/check-starter-projects.yml, .github/workflows/check.yml, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/local.kotlin.gradle.kts, lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/snippet/forannotationprovider/class-has-no-annotation2.kttxt, test-projects/konsist-path-tester/app/build.gradle.kts, test-projects/konsist-path-tester/build.gradle.kts, test-projects/konsist-path-tester/data/build.gradle.kts, test-projects/konsist-root-path-gradle-tester/app/build.gradle.kts, test-projects/konsist-root-path-gradle-tester/build.gradle.kts
Java version: `19` -> `21`
Java distribution: `zulu` -> `corretto`
=> Upgrade CI Java Version

DeveloperReadme.md, gradle.properties, lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/DeclarationKonsistTest.kt
Reverts LemonAppDev/konsist#916
=> Revert "Main To Develop"

DeveloperReadme.md, gradle.properties, lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/DeclarationKonsistTest.kt
Reverts LemonAppDev/konsist#918
=> Revert "Revert "Main To Develop""

lib/src/main/kotlin/com/lemonappdev/konsist/core/util/KotlinFileParser.kt
This PR: https://github.com/LemonAppDev/konsist/pull/1259 with passed tests
=> Add file information to getKtFile IllegalArgumentException

lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/util/KoFileDeclarationProvider.kt
We've seen a lot of test flakiness lately with Konsist, due to it trying to parse generated files during builds. Since we can't control when Konsist tests are ran during a parallel Gradle build, Konsist can very easily get into a state where it tries to read generated Kotlin files whilst they're being generated.
This PR makes getKoFileDeclarations() more permissive, so that it doesn't throw "File must be a Kotlin file" exceptions for files which disappear in between the initial filetree walk and parsing.
=> Make getKoFileDeclarations more permissive

scripts/create_release.py
1. Added the ability to create a release branch from the `develop` branch and increment the patch version.
2. Fixed error in `replace_konsist_version()` method
=> KON-641 Update script to create release

buildSrc/src/main/kotlin/local.kotlin.gradle.kts, lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoModifierProviderCore.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/tag/KoKDocTagProviderCore.kt
Make Konsist backwards compatible with Kotlin 1.8.
=> KON-648 Improve Kotlin Backwards Compatibility

lib/src/main/kotlin/com/lemonappdev/konsist/core/container/KoScopeCreatorCore.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/util/KoFileDeclarationProvider.kt
The current implementation has two issues, which can cause issues on larger projects:
- Currently getKoFileDeclarations() will parse _all_ Kotlin files in the project, including build files. They then later filtered out by KoScopeCreatorCore.getFiles, but this is very inefficient. We've seen lots of OOMs lately in our Konsist tests, and it seems to be because we also have a lot of generated Kotlin files.
- KoFileDeclarationProvider will try and launch `getKoFileDeclarations` from object init (which is basically when the class is loaded). I assume that this was done to preload the classes, but I think that is too aggressive. These should be lazily loaded when they're first needed, which will usually be the first test.
This PR changes this so that `getKoFileDeclarations` can be provided …
=> Optimize loading of KoFiles

lib/src/konsistTest/kotlin/com/lemonappdev/konsist/api/KdocKonsistTest.kt, lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/DeclarationKonsistTest.kt, lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/EnumKonsistTest.kt, lib/src/main/kotlin/com/lemonappdev/konsist/api/KoKDocTag.kt, lib/src/main/kotlin/com/lemonappdev/konsist/api/KoModifier.kt, lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/comparable/ComparableExt.kt, lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoNameProviderListExt.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/DependencyRulesCore.kt, lib/src/snippet/kotlin/com/lemonappdev/konsist/GeneralSnippets.ktdoc, lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoNameProviderListExtTest.kt, lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/comparable/ComparableExtTest.kt
```kotlin
fun `every class constructor has alphabetically ordered parameters`() {
val constructors = 
Konsist
.classes()
.constructors
// Before
.assertTrue {
val sortedNames = it
.parameters
.map { parameter -> parameter.name }
.sorted()
names == sortedNames
// Now
.assertTrue {
it.parameters.isSortedByName() // or it.parameters.isSortedBy { it.name }
}
}
}
```
=> KON-663 Add IsSortedByName And IsSortedBy Extensions

lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/AssertTrueOnDeclarationListTest.kt, lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/AssertTrueOnDeclarationSequenceTest.kt, lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/AssertTrueOnSingleDeclarationTest.kt, lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/AssertTrueOnProviderListTest.kt, lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/AssertTrueOnSingleProviderTest.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
Follow up for 
https://github.com/LemonAppDev/konsist/pull/1446
=> KON-661 Separate Declaration Name And Type In Errors2

lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/validator/ascii/AsciiTreeNode.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoArchitectureAssert.kt
- Add constructors to `AsciiTreeNode`
- Unify code
=> Refactor Asci Tree Node

gradle/libs.versions.toml, samples/starter-projects/kmp-gradle-kotlin-junit5/build.gradle.kts, samples/starter-projects/kmp-gradle-kotlin-kotest/build.gradle.kts, samples/starter-projects/spring-gradle-groovy-junit-5/build.gradle, samples/starter-projects/spring-gradle-groovy-kotest/build.gradle, samples/starter-projects/spring-gradle-kotlin-junit-5/build.gradle.kts, samples/starter-projects/spring-gradle-kotlin-kotest/build.gradle.kts, samples/starter-projects/spring-maven-junit5/pom.xml, samples/starter-projects/spring-maven-kotest/pom.xml, test-projects/konsist-declaration-tester/gradle/libs.versions.toml, test-projects/konsist-path-tester/gradle/libs.versions.toml, test-projects/konsist-root-path-gradle-tester/gradle/libs.versions.toml
Reverts LemonAppDev/konsist#1590
=> Revert "Update kotlin monorepo to v2.1.0"

lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparameters/KoParametersProviderExtTest.kt, lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparameters/snippet/declaration-with-non-tag-with-@-in-description-has-valid-kdoc.kttest, lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoKDocDeclarationCore.kt, lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/tag/KoKDocTagProviderCore.kt
Community: https://github.com/LemonAppDev/konsist/discussions/1595
=> KON-697 `hasValidKDocParamTags` not distinguish non-KDoc tags

lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/Layer.kt, lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt
Allow `Layer(name = "name", rootPackage = "com..example..")`
=> KON-700 Allow Layer Consecutive Dots In Middle Of Package Name

README.md, gradle.properties, gradle/libs.versions.toml, lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/Layer.kt, lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt, samples/starter-projects/android-gradle-groovy-junit-4/build.gradle, samples/starter-projects/android-gradle-groovy-junit-4/konsistTest/build.gradle, samples/starter-projects/android-gradle-groovy-junit-5/app/build.gradle, samples/starter-projects/android-gradle-groovy-junit-5/build.gradle, samples/starter-projects/android-gradle-groovy-junit-5/konsistTest/build.gradle, samples/starter-projects/android-gradle-groovy-kotest/build.gradle, samples/starter-projects/android-gradle-groovy-kotest/konsistTest/build.gradle, samples/starter-projects/android-gradle-kotlin-junit-4/build.gradle.kts, samples/starter-projects/android-gradle-kotlin-junit-4/konsistTest/build.gradle.kts, samples/starter-projects/android-gradle-kotlin-junit-5/build.gradle.kts, samples/starter-projects/android-gradle-kotlin-junit-5/konsistTest/build.gradle.kts, samples/starter-projects/android-gradle-kotlin-kotest/build.gradle.kts, samples/starter-projects/android-gradle-kotlin-kotest/konsistTest/build.gradle.kts, samples/starter-projects/kmp-gradle-kotlin-junit5/build.gradle.kts, samples/starter-projects/kmp-gradle-kotlin-junit5/konsistTest/build.gradle.kts, samples/starter-projects/kmp-gradle-kotlin-kotest/build.gradle.kts, samples/starter-projects/kmp-gradle-kotlin-kotest/konsistTest/build.gradle.kts, samples/starter-projects/spring-gradle-groovy-junit-5/build.gradle, samples/starter-projects/spring-gradle-groovy-kotest/build.gradle, samples/starter-projects/spring-gradle-kotlin-junit-5/build.gradle.kts, samples/starter-projects/spring-gradle-kotlin-kotest/build.gradle.kts, samples/starter-projects/spring-maven-junit5/pom.xml, samples/starter-projects/spring-maven-kotest/pom.xml
=> Release 0.17.2

README.md, gradle.properties, gradle/libs.versions.toml, lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/Layer.kt, lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt, samples/starter-projects/android-gradle-groovy-junit-4/build.gradle, samples/starter-projects/android-gradle-groovy-junit-4/konsistTest/build.gradle, samples/starter-projects/android-gradle-groovy-junit-5/app/build.gradle, samples/starter-projects/android-gradle-groovy-junit-5/build.gradle, samples/starter-projects/android-gradle-groovy-junit-5/konsistTest/build.gradle, samples/starter-projects/android-gradle-groovy-kotest/build.gradle, samples/starter-projects/android-gradle-groovy-kotest/konsistTest/build.gradle, samples/starter-projects/android-gradle-kotlin-junit-4/build.gradle.kts, samples/starter-projects/android-gradle-kotlin-junit-4/konsistTest/build.gradle.kts, samples/starter-projects/android-gradle-kotlin-junit-5/build.gradle.kts, samples/starter-projects/android-gradle-kotlin-junit-5/konsistTest/build.gradle.kts, samples/starter-projects/android-gradle-kotlin-kotest/build.gradle.kts, samples/starter-projects/android-gradle-kotlin-kotest/konsistTest/build.gradle.kts, samples/starter-projects/kmp-gradle-kotlin-junit5/build.gradle.kts, samples/starter-projects/kmp-gradle-kotlin-junit5/konsistTest/build.gradle.kts, samples/starter-projects/kmp-gradle-kotlin-kotest/build.gradle.kts, samples/starter-projects/kmp-gradle-kotlin-kotest/konsistTest/build.gradle.kts, samples/starter-projects/spring-gradle-groovy-junit-5/build.gradle, samples/starter-projects/spring-gradle-groovy-kotest/build.gradle, samples/starter-projects/spring-gradle-kotlin-junit-5/build.gradle.kts, samples/starter-projects/spring-gradle-kotlin-kotest/build.gradle.kts, samples/starter-projects/spring-maven-junit5/pom.xml, samples/starter-projects/spring-maven-kotest/pom.xml
* Update plugin com.android.application to v8.7.3 (#1604)
* Update plugin com.android.library to v8.7.3 (#1605)
* Update dependency com.lemonappdev:konsist to v0.17.1 (#1603)
* Update ktor monorepo to v3.0.2 (#1606)
* Update dependency com.pinterest.ktlint:ktlint-cli to v1.5.0 (#1607)
* Allow Layer consecutive dots in middle of package name
* Update Version to 0.17.2
---------
=> `main` to `develop`

gradle/libs.versions.toml, samples/starter-projects/android-gradle-groovy-junit-5/gradle/libs.versions.toml, samples/starter-projects/android-gradle-groovy-kotest/gradle/libs.versions.toml, samples/starter-projects/android-gradle-kotlin-junit-5/gradle/libs.versions.toml, samples/starter-projects/android-gradle-kotlin-kotest/gradle/libs.versions.toml, samples/starter-projects/kmp-gradle-kotlin-junit5/konsistTest/build.gradle.kts, samples/starter-projects/spring-gradle-groovy-junit-5/gradle/libs.versions.toml, samples/starter-projects/spring-gradle-kotlin-junit-5/gradle/libs.versions.toml, test-projects/konsist-declaration-tester/gradle/libs.versions.toml, test-projects/konsist-path-tester/gradle/libs.versions.toml, test-projects/konsist-root-path-gradle-tester/gradle/libs.versions.toml
Reverts LemonAppDev/konsist#1815
=> Revert "Update junit-framework monorepo to v6 (major)"
